import os
import subprocess
from pathlib import Path

def format_timestamp(ms: int) -> str:
    """
    Converts milliseconds into standard SRT format: HH:MM:SS,mmm
    """
    seconds, ms = divmod(int(ms), 1000)
    minutes, seconds = divmod(seconds, 60)
    hours, minutes = divmod(minutes, 60)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{ms:03d}"

def extract_audio(video_path: str, audio_path: str):
    """
    Extracts 16kHz mono audio from the video file using FFmpeg.
    16kHz mono is the optimal format for ASR models.
    """
    print(f"[*] Extracting audio from {video_path}...")
    command = [
        "ffmpeg", "-y", "-i", video_path,
        "-vn", "-acodec", "pcm_s16le",
        "-ar", "16000", "-ac", "1", audio_path
    ]
    try:
        # Run FFmpeg silently, throw exception on failure
        subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, check=True)
        print("[*] Audio extraction successful.")
    except subprocess.CalledProcessError as e:
        print(f"FFmpeg error: {e.stderr.decode()}")
        raise RuntimeError("Failed to extract audio. Please ensure FFmpeg is installed and added to your system PATH.")

def generate_srt_from_audio(audio_path: str, srt_path: str):
    """
    Transcribes the audio using FunASR and writes the output directly to an SRT file.
    """
    try:
        from funasr import AutoModel
    except ImportError:
        raise ImportError("Please install FunASR and its dependencies: pip install funasr modelscope torchaudio")

    print("[*] Initializing FunASR model (this may take a moment to download weights on first run)...")
    
    # We use paraformer with VAD and Punctuation models. 
    # VAD is strictly required to get accurate sentence-level timestamp boundaries.
    model = AutoModel(
        model="paraformer-zh",
        vad_model="fsmn-vad",
        punc_model="ct-punc",
        disable_update=True
    )

    print("[*] Transcribing audio...")
    # sentence_timestamp=True forces the model to return precise start/end times
    res = model.generate(
        input=audio_path,
        batch_size_s=300,
        sentence_timestamp=True
    )

    if not res or len(res) == 0:
        raise ValueError("No transcription results were returned from the model.")

    data = res[0]
    
    # Extract the sentence boundary array generated by FunASR
    sentence_info = data.get("sentence_info", [])

    if not sentence_info:
        raise ValueError("The model did not return sentence boundaries. Ensure VAD is functioning properly.")

    print(f"[*] Writing SRT file to {srt_path}...")
    with open(srt_path, "w", encoding="utf-8") as f:
        for i, seg in enumerate(sentence_info, start=1):
            start_time = format_timestamp(seg.get("start", 0))
            end_time = format_timestamp(seg.get("end", 0))
            text = seg.get("text", "").strip()

            # SRT Format Structure:
            # 1
            # 00:00:00,000 --> 00:00:02,500
            # Subtitle text
            f.write(f"{i}\n")
            f.write(f"{start_time} --> {end_time}\n")
            f.write(f"{text}\n\n")

    print("[*] SRT generation complete!")

def process_video(video_file: str):
    """
    Main orchestrator function.
    """
    if not os.path.exists(video_file):
        raise FileNotFoundError(f"Video file not found: {video_file}")

    # Set up file paths dynamically based on the input video
    base_name = os.path.splitext(video_file)[0]
    audio_file = f"{base_name}_extracted.wav"
    srt_file = f"{base_name}.srt"

    try:
        # 1. Extract the audio
        extract_audio(video_file, audio_file)
        
        # 2. Transcribe and generate SRT
        generate_srt_from_audio(audio_file, srt_file)
        
    finally:
        # 3. Cleanup: remove the temporary huge WAV file to save disk space
        if os.path.exists(audio_file):
            os.remove(audio_file)
            print("[*] Cleaned up temporary audio file.")
            
    print(f"\nSUCCESS: Your subtitles are ready at -> {srt_file}")


# ============================================================
# SubtitleExtractor class — used by app.py for multiple backends
# ============================================================

class SubtitleExtractor:
    """Extract subtitles from video using various ASR backends."""

    PROVIDER_CAPABILITIES = {
        "faster_whisper": {"max_duration": None, "offline": True, "languages": ["zh", "en", "ja", "ko", "fr", "de", "es"]},
        "funasr": {"max_duration": "12h", "offline": False, "languages": ["zh", "en", "ja", "yue"]},
        "qwen-asr": {"max_duration": "12h", "offline": False, "languages": ["zh", "en", "ja", "yue"]},
        "qwen3-asr-flash-filetrans": {"max_duration": "12h", "offline": False, "languages": ["zh", "en", "ja", "yue", "ko", "fr", "de", "es", "ru", "pt", "it", "tr", "ar", "th", "vi"], "features": ["emotion", "speaker_diarization", "itn"]},
        "openai": {"max_duration": "25MB", "offline": False, "languages": "auto"},
        "gemini": {"max_duration": "2GB", "offline": False, "languages": "auto"},
        "qwen": {"max_duration": "2GB", "offline": False, "languages": "auto"},
        "deepseek": {"max_duration": "2GB", "offline": False, "languages": "auto"},
    }

    def __init__(self, provider: str = "faster_whisper", project_dir: Path = None, **kwargs):
        self.provider = provider.strip()
        self.config = kwargs
        self.project_dir = Path(project_dir) if project_dir else None

        if self.provider not in self.PROVIDER_CAPABILITIES:
            available = ", ".join(self.PROVIDER_CAPABILITIES.keys())
            raise ValueError(f"Unknown provider: '{self.provider}'. Available: {available}")

    def extract(self, video_path: str, language: str = "zh"):
        if not os.path.exists(video_path):
            raise FileNotFoundError(f"Video file not found: {video_path}")

        if self.provider == "faster_whisper":
            return self._extract_faster_whisper(video_path, language)
        elif self.provider == "funasr":
            return self._extract_funasr(video_path, language)
        elif self.provider == "qwen-asr":
            return self._extract_qwen_asr(video_path, language)
        elif self.provider == "qwen3-asr-flash-filetrans":
            return self._extract_qwen3_asr_flash_filetrans(video_path, language)
        elif self.provider in ("openai", "gemini", "qwen", "deepseek"):
            return self._extract_via_api(video_path, language)
        else:
            raise ValueError(f"Unknown provider: {self.provider}")

    def _extract_audio(self, video_path: str) -> str:
        """Extract 16kHz mono WAV to project audio dir or temp."""
        if self.project_dir:
            audio_dir = self.project_dir / "audio"
            audio_dir.mkdir(parents=True, exist_ok=True)
            audio_path = str(audio_dir / "video_audio.wav")
        else:
            import tempfile
            audio_path = tempfile.mktemp(suffix=".wav")
        cmd = f'ffmpeg -y -i "{video_path}" -vn -ar 16000 -ac 1 -c:a pcm_s16le "{audio_path}"'
        subprocess.run(cmd, shell=True, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return audio_path

    def _cleanup_temp(self, audio_path: Path):
        if self.project_dir:
            return
        try:
            if audio_path.exists():
                audio_path.unlink()
        except Exception:
            pass

    def _extract_faster_whisper(self, video_path: str, language: str):
        try:
            from faster_whisper import WhisperModel
        except ImportError:
            raise ImportError("faster-whisper not installed. Run: pip install faster-whisper")

        model_size = self.config.get("model_size", "medium")
        device = self.config.get("device", "auto")
        compute_type = self.config.get("compute_type", "float16" if device == "cuda" else "int8")
        print(f"[SubtitleExtractor] Loading faster-whisper model: {model_size} on {device}...")
        model = WhisperModel(model_size, device=device, compute_type=compute_type)

        print(f"[SubtitleExtractor] Transcribing {video_path}...")
        segments, info = model.transcribe(
            video_path,
            language=language if language != "auto" else None,
            beam_size=self.config.get("beam_size", 5),
            word_timestamps=self.config.get("word_timestamps", False),
        )
        print(f"[SubtitleExtractor] Detected language: {info.language} (prob: {info.language_probability:.2f})")

        subtitles = []
        for segment in segments:
            subtitles.append({"text": segment.text.strip(), "start": segment.start, "end": segment.end})
        print(f"[SubtitleExtractor] Extracted {len(subtitles)} subtitle segments.")
        return subtitles

    def _extract_funasr(self, video_path: str, language: str):
        return self._extract_qwen_asr(video_path, language, model="fun-asr")

    def _extract_qwen_asr(self, video_path: str, language: str, model: str = "fun-asr"):
        """Extract subtitles via pure HTTP API — no DashScope SDK needed."""
        import requests as _req
        import time as _time

        api_key = (self.config.get("api_key") or os.getenv("QWEN_API_KEY") or os.getenv("DASHSCOPE_API_KEY") or "").strip()
        if not api_key:
            raise ValueError("No DashScope API key configured.")

        base_url = (self.config.get("base_url") or os.getenv("QWEN_BASE_URL") or "https://dashscope-intl.aliyuncs.com").strip()
        api_host = base_url.split("/compatible-mode")[0].split("/api")[0]
        headers = {"Authorization": f"Bearer {api_key}"}

        audio_path = Path(self._extract_audio(video_path))
        print(f"[SubtitleExtractor] Audio ready: {audio_path}")

        try:
            # 1. Upload via POST /api/v1/files
            print(f"[SubtitleExtractor] Uploading audio to DashScope...")
            with open(audio_path, "rb") as f:
                up = _req.post(f"{api_host}/api/v1/files", headers=headers,
                               files={"file": ("audio.wav", f, "audio/wav")}, timeout=300)
            if up.status_code != 200:
                raise RuntimeError(f"Upload failed: {up.status_code} {up.text}")
            fid = up.json().get("data", {}).get("uploaded_files", [{}])[0].get("file_id", "")
            if not fid:
                raise RuntimeError(f"No file_id: {up.text}")
            file_url = f"fileid://{fid}"
            print(f"[SubtitleExtractor] Uploaded, fileid={fid}")

            # 2. Submit transcription (must use async mode — synchronous not supported)
            print(f"[SubtitleExtractor] Submitting {model} transcription...")
            task = _req.post(f"{api_host}/api/v1/services/audio/asr/transcription",
                             headers={**headers, "Content-Type": "application/json", "X-DashScope-Async": "enable"},
                             json={"model": model, "input": {"file_urls": [file_url]}}, timeout=60)
            if task.status_code != 200:
                raise RuntimeError(f"Submit failed: {task.status_code} {task.text}")
            tid = task.json().get("output", {}).get("task_id", "")
            if not tid:
                raise RuntimeError(f"No task_id: {task.text}")

            # 3. Poll for results
            print(f"[SubtitleExtractor] Polling task {tid}...")
            subtitles = []
            for _ in range(300):
                _time.sleep(2)
                p = _req.get(f"{api_host}/api/v1/tasks/{tid}", headers=headers, timeout=30)
                if p.status_code != 200:
                    continue
                pd = p.json()
                st = pd.get("output", {}).get("task_status", "")
                if st == "SUCCEEDED":
                    for ri in pd.get("output", {}).get("results", []):
                        if ri.get("subtask_status") != "SUCCEEDED":
                            continue
                        tu = ri.get("transcription_url", "")
                        if not tu:
                            continue
                        jr = _req.get(tu, timeout=60)
                        if jr.status_code != 200:
                            continue
                        jd = jr.json()
                        items = jd.get("transcripts") or jd.get("sentences") or []
                        for s in items:
                            text = s.get("text", "").strip()
                            if not text:
                                continue
                            begin_ms = float(s.get("begin_time") or s.get("start_time", 0))
                            end_ms = float(s.get("end_time", 0))
                            subtitles.append({
                                "text": text,
                                "start": round(begin_ms / 1000.0, 2),
                                "end": round(end_ms / 1000.0, 2),
                            })
                    break
                elif st in ("FAILED", "CANCELED"):
                    print(f"[SubtitleExtractor] Task {st}: {pd.get('output', {}).get('message', '')}")
                    break

            if not subtitles:
                subtitles.append({"text": "（ASR 未返回结果）", "start": 0, "end": 0})
            print(f"[SubtitleExtractor] {model}: {len(subtitles)} segments")
            return subtitles

        except Exception as e:
            print(f"[SubtitleExtractor] HTTP upload+ASR failed: {e}")
            import traceback
            traceback.print_exc()
            raise
        finally:
            self._cleanup_temp(audio_path)

    def _extract_qwen3_asr_flash_filetrans(self, video_path: str, language: str):
        """Extract subtitles using Qwen3-ASR-Flash-Filetrans via async HTTP API."""
        import requests as _req
        import time as _time

        api_key = (self.config.get("api_key") or os.getenv("QWEN_API_KEY") or os.getenv("DASHSCOPE_API_KEY") or "").strip()
        if not api_key:
            raise ValueError("No DashScope API key configured.")

        model = self.config.get("model", "qwen3-asr-flash-filetrans")
        region = self.config.get("region", "intl")
        base_url = "https://dashscope-intl.aliyuncs.com/api/v1" if region == "intl" else "https://dashscope.aliyuncs.com/api/v1"

        audio_path = Path(self._extract_audio(video_path))
        print(f"[SubtitleExtractor] Audio ready: {audio_path}")

        try:
            # Upload
            print(f"[SubtitleExtractor] Uploading audio...")
            headers = {"Authorization": f"Bearer {api_key}"}
            with open(audio_path, "rb") as f:
                up = _req.post(f"{base_url}/files", headers=headers,
                               files={"file": ("audio.wav", f, "audio/wav")}, timeout=300)
            if up.status_code != 200:
                raise RuntimeError(f"Upload failed: {up.status_code} {up.text}")
            res_json = up.json()
            result_data = res_json.get("data") or res_json.get("output") or {}
            file_url = result_data.get("uploaded_files", [{}])[0].get("url", "")
            if not file_url:
                fid = result_data.get("uploaded_files", [{}])[0].get("file_id", "")
                if fid:
                    file_url = f"fileid://{fid}"
                else:
                    raise RuntimeError("Upload failed: No URL found")
            print(f"[SubtitleExtractor] Uploaded: {file_url[:60]}...")

            # Submit async task
            submit_url = f"{base_url}/services/audio/asr/transcription"
            async_headers = {**headers, "Content-Type": "application/json", "X-DashScope-Async": "enable"}
            payload = {
                "model": model,
                "input": {"file_urls": [file_url]},
                "parameters": {
                    "enable_itn": self.config.get("enable_itn", False),
                    "enable_words": self.config.get("enable_words", True),
                }
            }
            if language:
                payload["parameters"]["language"] = language

            print(f"[SubtitleExtractor] Submitting async task for {model}...")
            response = _req.post(submit_url, headers=async_headers, json=payload, timeout=30)
            if response.status_code == 401:
                raise ValueError("Authentication Error (401): Invalid API key.")
            if response.status_code != 200:
                raise RuntimeError(f"Submit failed: {response.status_code} {response.text}")

            task_id = response.json().get("output", {}).get("task_id")
            if not task_id:
                raise RuntimeError(f"No task_id in response")

            # Poll
            print(f"[SubtitleExtractor] Polling task {task_id}...")
            query_url = f"{base_url}/tasks/{task_id}"
            poll_headers = {"Authorization": f"Bearer {api_key}", "X-DashScope-Async": "enable"}

            for _ in range(300):
                _time.sleep(2)
                sr = _req.get(query_url, headers=poll_headers, timeout=30)
                if sr.status_code != 200:
                    continue
                sd = sr.json()
                st = sd.get("output", {}).get("task_status", "")
                if st == "SUCCEEDED":
                    results = sd.get("output", {}).get("results", [])
                    tu = (results[0].get("transcription_url") if results else
                          sd.get("output", {}).get("result", {}).get("transcription_url"))
                    if not tu:
                        raise RuntimeError("No transcription_url in response")
                    jr = _req.get(tu, timeout=60)
                    jd = jr.json()
                    subtitles = []
                    items = jd.get("transcripts") or jd.get("sentences") or []
                    for s in items:
                        text = s.get("text", "").strip()
                        if not text:
                            continue
                        begin_ms = float(s.get("begin_time") or s.get("start_time", 0))
                        end_ms = float(s.get("end_time", 0))
                        entry = {"text": text, "start": round(begin_ms / 1000.0, 2), "end": round(end_ms / 1000.0, 2)}
                        if "speaker_id" in s:
                            entry["speaker"] = f"Speaker_{s['speaker_id']}"
                        subtitles.append(entry)
                    print(f"[SubtitleExtractor] Extracted {len(subtitles)} segments")
                    return subtitles
                elif st in ("FAILED", "CANCELED", "UNKNOWN"):
                    raise RuntimeError(f"Task {st}: {sd.get('output', {}).get('message', '')}")

            raise RuntimeError("Task polling timed out")
        except Exception as e:
            print(f"[SubtitleExtractor] Error: {e}")
            import traceback
            traceback.print_exc()
            raise
        finally:
            self._cleanup_temp(audio_path)

    def _extract_via_api(self, video_path: str, language: str):
        """Placeholder for API-based extraction (OpenAI/Gemini/Qwen/DeepSeek)."""
        raise NotImplementedError(
            f"{self.provider} multimodal transcription not fully implemented. "
            f"Use 'qwen3-asr-flash-filetrans' for DashScope ASR."
        )


if __name__ == "__main__":
    # Point this to your uploaded video file
    VIDEO_INPUT = "your_uploaded_video.mp4" 
    process_video(VIDEO_INPUT)